// This GUI file is generated by guibuilder version 4.2.2
//////////
f=figure('figure_position',[100,100],'figure_size',[420,260],'auto_resize','on','background',[8],'figure_name','myGUI','color_map',[],'dockable','off','infobar_visible','off','toolbar_visible','off','menubar_visible','off','default_axes','on','visible','off');
//////////
handles.dummy = 0;
handles.OkButton=uicontrol(f,'unit','normalized','BackgroundColor',[],'Enable',[],'FontAngle',[],'FontName',[],'FontSize',[],'FontUnits',[],'FontWeight',[],'ForegroundColor',[],'HorizontalAlignment',[],'ListboxTop',[],'Max',[],'Min',[],'Position',[20,200,80,25],'Relief',[],'SliderStep',[],'String','OK','Style','pushbutton','Value',[0],'VerticalAlignment',[],'Visible',[],'Tag','OkButton','Callback','OkButton_callback(handles)')
handles.CancelButton=uicontrol(f,'unit','normalized','BackgroundColor',[],'Enable',[],'FontAngle',[],'FontName',[],'FontSize',[],'FontUnits',[],'FontWeight',[],'ForegroundColor',[],'HorizontalAlignment',[],'ListboxTop',[],'Max',[],'Min',[],'Position',[110,200,80,25],'Relief',[],'SliderStep',[],'String','Cancel','Style','pushbutton','Value',[0],'VerticalAlignment',[],'Visible',[],'Tag','CancelButton','Callback','CancelButton_callback(handles)')
handles.InputEdit=uicontrol(f,'unit','normalized','BackgroundColor',[],'Enable',[],'FontAngle',[],'FontName',[],'FontSize',[],'FontUnits',[],'FontWeight',[],'ForegroundColor',[],'HorizontalAlignment',[],'ListboxTop',[],'Max',[],'Min',[],'Position',[20,150,170,25],'Relief',[],'SliderStep',[],'String','','Style','edit','Value',[0],'VerticalAlignment',[],'Visible',[],'Tag','InputEdit','Callback',[])


f.visible = "on";


//////////
// Callbacks are defined as below. Please do not delete the comments as it will be used in coming version
//////////

function OkButton_callback(handles)
//Write your callback for  OkButton  here


endfunction


function CancelButton_callback(handles)
//Write your callback for  CancelButton  here


endfunction

