// Copyright (C) 2026 - Scilab macOS/2027 modernization
//
// This file is hereby licensed under the terms of the GNU GPL v2.0,
// pursuant to article 5.3.4 of the CeCILL v.2.1.
// This file was originally licensed under the terms of the CeCILL v2.1,
// and continues to be available under such terms.
// For more information, see the COPYING file which you should have received
// along with this program.

// Step 3 of docs/design/dynamic-link-cmake-migration.md: emit a DECLARATIVE
// CMakeLists.txt that calls scilab_gateway(), as the replacement for the
// autotools skeleton's Makefile.orig + scicompile.sh rewriting.
//
// Since step 6 this is the DEFAULT generator. The autotools skeleton is reached
// only via SCILAB_GATEWAY_BUILD=autotools, which warns on every use; see
// ilib_gateway_use_cmake().
//
// The generated file is deliberately self-contained and readable: it pins the
// Scilab it was generated against rather than relying on a CMAKE_PREFIX_PATH
// the user would have to supply, so a toolbox author can open it, run
// `cmake -S . -B build` by hand, and debug their gateway with normal tools.
// That inspectability is one of the reasons CMake was chosen over emitting a
// plain Makefile (section 1 of the design doc).

function ilib_gen_cmake_unix(libname, filelist, ldflags, cflags, fflags, cc, buildDir)

    // Escape a string for embedding in a CMake quoted argument. Backslash first
    // -- escaping quotes first would then double the backslashes it inserted.
    function s = cmakeQuote(s)
        s = strsubst(s, "\", "\\");
        s = strsubst(s, """", "\""");
    endfunction

    // filelist arrives as the single space-separated string scicompile.sh is
    // handed. Headers are in it because automake tolerates them in _SOURCES;
    // CMake would try to treat an unknown extension as a source, so keep only
    // what a compiler is actually invoked on.
    allFiles = tokens(stripblanks(filelist), " ");
    sources  = [];
    langC = %f; langCXX = %f; langF = %f;
    for f = allFiles(:)'
        if f == "" then continue; end
        [p, n, e] = fileparts(f);
        select convstr(e, "l")
        case ".c"     then sources = [sources; f]; langC   = %t;
        case ".cpp"   then sources = [sources; f]; langCXX = %t;
        case ".cxx"   then sources = [sources; f]; langCXX = %t;
        case ".cc"    then sources = [sources; f]; langCXX = %t;
        case ".f"     then sources = [sources; f]; langF   = %t;
        case ".f90"   then sources = [sources; f]; langF   = %t;
        case ".f95"   then sources = [sources; f]; langF   = %t;
        else
            // .h/.hxx and anything else: not compiled, not an error.
        end
    end

    if isempty(sources) then
        error(msprintf(_("%s: no compilable source found for library ''%s''.\n"), ..
                       "ilib_gen_cmake", libname));
    end

    // The generated wrapper is C++, so CXX is always enabled -- see invariant 1
    // in section 11 of the design doc (the link driver must be C++ even for a
    // gateway whose every user source is C). Enabling a language Scilab has no
    // compiler for would fail at project() time, so only enable what is used.
    langs = "CXX";
    if langC then langs = "C " + langs; end
    if langF then langs = langs + " Fortran"; end

    txt = [];
    txt = [txt; "# Generated by ilib_gen_Make for the Scilab toolbox gateway ''" + libname + "''."];
    txt = [txt; "# Do not edit: regenerated on every ilib_build."];
    txt = [txt; "#"];
    txt = [txt; "# You can build this by hand for debugging:  cmake -S . -B build && cmake --build build"];
    txt = [txt; "cmake_minimum_required(VERSION 3.20)"];

    // A compiler override has to precede project(), which is what latches the
    // toolchain; setting it afterwards is silently ignored.
    //
    // The `cc` argument is a COMMAND, not just a program: sciTorch passes
    // "clang++ -x c++" to force its C sources through the C++ front end. make
    // runs $(CC) through a shell, so the arguments come along for free.
    // CMAKE_<LANG>_COMPILER is a single executable PATH -- handed the whole
    // string it reports:
    //
    //     The CMAKE_CXX_COMPILER: clang++ -x c++
    //     is not a full path and was not found in the PATH.
    //
    // So split it: first token is the compiler, the rest are compile flags. They
    // must reach the compile line, or "-x c++" is silently dropped and the C
    // sources get compiled as C -- which would build and then fail at link with
    // mangled-name mismatches, far from the cause.
    ccExtra = "";
    if cc <> "" then
        ccTok = tokens(stripblanks(cc), [" ", ascii(9)]);
        txt = [txt; "set(CMAKE_C_COMPILER """ + cmakeQuote(ccTok(1)) + """)"];
        txt = [txt; "set(CMAKE_CXX_COMPILER """ + cmakeQuote(ccTok(1)) + """)"];
        if size(ccTok, "*") > 1 then
            ccExtra = strcat(ccTok(2:$), " ");
        end
    end

    txt = [txt; "project(" + libname + "_gateway " + langs + ")"];
    txt = [txt; ""];
    // automake's default is -g -O2 for every language. On the autotools path
    // only C++ and Fortran actually get it: the Scilab launcher exports CFLAGS
    // (carrying the configure-detected Homebrew -I), and configure lets an
    // environment CFLAGS REPLACE the default rather than extend it, while
    // CXXFLAGS and FFLAGS are not exported and keep theirs. The captured oracle
    // shows the result plainly -- C: no -g, no -O2; C++/Fortran: both. So every
    // C gateway source in every toolbox is compiled unoptimized today.
    //
    // Apply it uniformly here. -DNDEBUG is deliberately NOT added (that is what
    // a bare CMAKE_BUILD_TYPE=Release/RelWithDebInfo would bring, and automake
    // never set it for toolboxes -- assert() must keep working as it does now).
    // A caller's own cflags are applied per target, i.e. AFTER these, so an
    // explicit -O0 from a toolbox author still wins.
    txt = [txt; "if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)"];
    txt = [txt; "  add_compile_options(-g -O2)"];
    txt = [txt; "endif()"];
    txt = [txt; ""];
    // Pin the generating Scilab by path rather than leaving discovery to the
    // environment: this build is only ever meaningful against the installation
    // whose headers it was generated from.
    txt = [txt; "find_package(Scilab REQUIRED"];
    txt = [txt; "  PATHS """ + cmakeQuote(SCI) + "/cmake"""];
    txt = [txt; "  NO_DEFAULT_PATH)"];
    txt = [txt; ""];

    // Caller flags are passed as ONE "SHELL:" item rather than a separated list.
    //
    // This is not cosmetic. CMake DE-DUPLICATES compile options, and real
    // toolboxes use space-separated option pairs -- sciFinance passes
    // "-isystem /opt/homebrew/opt/gettext/include -isystem /opt/homebrew/opt/boost/include".
    // Split into a plain list, the repeated `-isystem` collapses to one, and the
    // orphaned path becomes a bare argument: it stops being an include and turns
    // up on the LINK line, where clang reports "'linker' input unused" and the
    // compile then fails on a header it can no longer find. Both symptoms, one
    // cause.
    //
    // "SHELL:" is CMake's documented escape hatch for exactly this: the string is
    // split the way a shell would and is exempt from de-duplication, so option
    // pairs survive intact. It is why these are emitted verbatim instead of
    // through separate_arguments().
    txt = [txt; ""];

    txt = [txt; "scilab_gateway(" + libname];
    txt = [txt; "  SOURCES"];
    for s = sources(:)'
        txt = [txt; "    """ + cmakeQuote(s) + """"];
    end
    // Arguments carried by the `cc` override (e.g. sciTorch's "-x c++") ride
    // with the compile flags, since CMAKE_<LANG>_COMPILER can only hold the
    // executable. Placed FIRST so a caller's own cflags can still override.
    cAll = stripblanks(ccExtra + " " + cflags);
    if cAll <> "" then
        // CXX gets the same flags as C: gencompilationflags_unix emits one
        // CFLAGS value and passes it as both CFLAGS and CXXFLAGS to make.
        txt = [txt; "  C_FLAGS ""SHELL:" + cmakeQuote(cAll) + """"];
        txt = [txt; "  CXX_FLAGS ""SHELL:" + cmakeQuote(cAll) + """"];
    end
    if fflags <> "" then
        txt = [txt; "  Fortran_FLAGS ""SHELL:" + cmakeQuote(fflags) + """"];
    end
    if ldflags <> "" then
        txt = [txt; "  LINK_FLAGS ""SHELL:" + cmakeQuote(ldflags) + """"];
    end
    // ilib_compile looks for the built library at .libs/<lib_name> inside the
    // build directory -- the libtool layout it has always read. Keep it.
    txt = [txt; "  OUTPUT_DIRECTORY ""${CMAKE_CURRENT_BINARY_DIR}/.libs"")"];

    // NOTE on the `libs` argument of ilib_build: it is deliberately NOT linked
    // here, because ilib_gen_Make_unix does not link it either -- it accepts
    // `libs` and never uses it. Those libraries are link()ed by the generated
    // loader.sce BEFORE the gateway is loaded, and the gateway itself is built
    // with -undefined dynamic_lookup, so their symbols resolve at dlopen time.
    // Linking them here would change the recorded dependencies and break parity
    // with the artifact the autotools path produces.

    outf = fullfile(buildDir, "CMakeLists.txt");
    mputl(txt, outf);

    if ( ilib_verbose() == 2 ) then
        mprintf(gettext("   %s: Generated %s (languages: %s).\n"), "ilib_gen_cmake", outf, langs);
    end

endfunction
