// Copyright (C) 2026 - Scilab macOS/2027 modernization
//
// This file is hereby licensed under the terms of the GNU GPL v2.0,
// pursuant to article 5.3.4 of the CeCILL v.2.1.
// This file was originally licensed under the terms of the CeCILL v2.1,
// and continues to be available under such terms.
// For more information, see the COPYING file which you should have received
// along with this program.

// Step 3 of docs/design/dynamic-link-cmake-migration.md: emit a DECLARATIVE
// CMakeLists.txt that calls scilab_gateway(), as the replacement for the
// autotools skeleton's Makefile.orig + scicompile.sh rewriting.
//
// Generation only. ilib_compile still runs `make` unless the build is switched
// over (step 4); with SCILAB_GATEWAY_BUILD=both the two generators run
// side by side so their outputs can be diffed on real toolboxes.
//
// The generated file is deliberately self-contained and readable: it pins the
// Scilab it was generated against rather than relying on a CMAKE_PREFIX_PATH
// the user would have to supply, so a toolbox author can open it, run
// `cmake -S . -B build` by hand, and debug their gateway with normal tools.
// That inspectability is one of the reasons CMake was chosen over emitting a
// plain Makefile (section 1 of the design doc).

function ilib_gen_cmake_unix(libname, filelist, ldflags, cflags, fflags, cc, buildDir)

    // Escape a string for embedding in a CMake quoted argument. Backslash first
    // -- escaping quotes first would then double the backslashes it inserted.
    function s = cmakeQuote(s)
        s = strsubst(s, "\", "\\");
        s = strsubst(s, """", "\""");
    endfunction

    // filelist arrives as the single space-separated string scicompile.sh is
    // handed. Headers are in it because automake tolerates them in _SOURCES;
    // CMake would try to treat an unknown extension as a source, so keep only
    // what a compiler is actually invoked on.
    allFiles = tokens(stripblanks(filelist), " ");
    sources  = [];
    langC = %f; langCXX = %f; langF = %f;
    for f = allFiles(:)'
        if f == "" then continue; end
        [p, n, e] = fileparts(f);
        select convstr(e, "l")
        case ".c"     then sources = [sources; f]; langC   = %t;
        case ".cpp"   then sources = [sources; f]; langCXX = %t;
        case ".cxx"   then sources = [sources; f]; langCXX = %t;
        case ".cc"    then sources = [sources; f]; langCXX = %t;
        case ".f"     then sources = [sources; f]; langF   = %t;
        case ".f90"   then sources = [sources; f]; langF   = %t;
        case ".f95"   then sources = [sources; f]; langF   = %t;
        else
            // .h/.hxx and anything else: not compiled, not an error.
        end
    end

    if isempty(sources) then
        error(msprintf(_("%s: no compilable source found for library ''%s''.\n"), ..
                       "ilib_gen_cmake", libname));
    end

    // The generated wrapper is C++, so CXX is always enabled -- see invariant 1
    // in section 11 of the design doc (the link driver must be C++ even for a
    // gateway whose every user source is C). Enabling a language Scilab has no
    // compiler for would fail at project() time, so only enable what is used.
    langs = "CXX";
    if langC then langs = "C " + langs; end
    if langF then langs = langs + " Fortran"; end

    txt = [];
    txt = [txt; "# Generated by ilib_gen_Make for the Scilab toolbox gateway ''" + libname + "''."];
    txt = [txt; "# Do not edit: regenerated on every ilib_build."];
    txt = [txt; "#"];
    txt = [txt; "# You can build this by hand for debugging:  cmake -S . -B build && cmake --build build"];
    txt = [txt; "cmake_minimum_required(VERSION 3.20)"];

    // A compiler override has to precede project(), which is what latches the
    // toolchain; setting it afterwards is silently ignored.
    if cc <> "" then
        txt = [txt; "set(CMAKE_C_COMPILER """ + cmakeQuote(cc) + """)"];
        txt = [txt; "set(CMAKE_CXX_COMPILER """ + cmakeQuote(cc) + """)"];
    end

    txt = [txt; "project(" + libname + "_gateway " + langs + ")"];
    txt = [txt; ""];
    // automake's default is -g -O2 for every language. On the autotools path
    // only C++ and Fortran actually get it: the Scilab launcher exports CFLAGS
    // (carrying the configure-detected Homebrew -I), and configure lets an
    // environment CFLAGS REPLACE the default rather than extend it, while
    // CXXFLAGS and FFLAGS are not exported and keep theirs. The captured oracle
    // shows the result plainly -- C: no -g, no -O2; C++/Fortran: both. So every
    // C gateway source in every toolbox is compiled unoptimized today.
    //
    // Apply it uniformly here. -DNDEBUG is deliberately NOT added (that is what
    // a bare CMAKE_BUILD_TYPE=Release/RelWithDebInfo would bring, and automake
    // never set it for toolboxes -- assert() must keep working as it does now).
    // A caller's own cflags are applied per target, i.e. AFTER these, so an
    // explicit -O0 from a toolbox author still wins.
    txt = [txt; "if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)"];
    txt = [txt; "  add_compile_options(-g -O2)"];
    txt = [txt; "endif()"];
    txt = [txt; ""];
    // Pin the generating Scilab by path rather than leaving discovery to the
    // environment: this build is only ever meaningful against the installation
    // whose headers it was generated from.
    txt = [txt; "find_package(Scilab REQUIRED"];
    txt = [txt; "  PATHS """ + cmakeQuote(SCI) + "/cmake"""];
    txt = [txt; "  NO_DEFAULT_PATH)"];
    txt = [txt; ""];

    // Caller flags arrive as opaque command-line strings. separate_arguments
    // splits them the way a shell would, so quoted -I paths with spaces survive;
    // splitting on whitespace here would break them.
    if cflags <> "" then
        txt = [txt; "separate_arguments(GW_C_FLAGS NATIVE_COMMAND """ + cmakeQuote(cflags) + """)"];
    end
    if fflags <> "" then
        txt = [txt; "separate_arguments(GW_F_FLAGS NATIVE_COMMAND """ + cmakeQuote(fflags) + """)"];
    end
    if ldflags <> "" then
        txt = [txt; "separate_arguments(GW_LD_FLAGS NATIVE_COMMAND """ + cmakeQuote(ldflags) + """)"];
    end
    txt = [txt; ""];

    txt = [txt; "scilab_gateway(" + libname];
    txt = [txt; "  SOURCES"];
    for s = sources(:)'
        txt = [txt; "    """ + cmakeQuote(s) + """"];
    end
    if cflags <> "" then
        // CXX gets the same flags as C: gencompilationflags_unix emits one
        // CFLAGS value and passes it as both CFLAGS and CXXFLAGS to make.
        txt = [txt; "  C_FLAGS ${GW_C_FLAGS}"];
        txt = [txt; "  CXX_FLAGS ${GW_C_FLAGS}"];
    end
    if fflags <> "" then
        txt = [txt; "  Fortran_FLAGS ${GW_F_FLAGS}"];
    end
    if ldflags <> "" then
        txt = [txt; "  LINK_FLAGS ${GW_LD_FLAGS}"];
    end
    // ilib_compile looks for the built library at .libs/<lib_name> inside the
    // build directory -- the libtool layout it has always read. Keep it.
    txt = [txt; "  OUTPUT_DIRECTORY ""${CMAKE_CURRENT_BINARY_DIR}/.libs"")"];

    // NOTE on the `libs` argument of ilib_build: it is deliberately NOT linked
    // here, because ilib_gen_Make_unix does not link it either -- it accepts
    // `libs` and never uses it. Those libraries are link()ed by the generated
    // loader.sce BEFORE the gateway is loaded, and the gateway itself is built
    // with -undefined dynamic_lookup, so their symbols resolve at dlopen time.
    // Linking them here would change the recorded dependencies and break parity
    // with the artifact the autotools path produces.

    outf = fullfile(buildDir, "CMakeLists.txt");
    mputl(txt, outf);

    if ( ilib_verbose() == 2 ) then
        mprintf(gettext("   %s: Generated %s (languages: %s).\n"), "ilib_gen_cmake", outf, langs);
    end

endfunction
