#!/usr/bin/env bash
# -quit must quit even when stdin is a pipe that stays OPEN and never sends EOF.
#
# THE DEFECT (fixed in modules/startup/src/cpp/scilab.cpp)
# -------------------------------------------------------
# When stdin was not a tty, Scilab swapped in getPipeLine() and then DISCARDED
# -quit -- "quit will be generated by the close of the pipeline". That holds for
# a pipe that ends (`echo cmd | scilab`, `< file scilab`) and fails for one that
# merely stays open. java.lang.Runtime.exec hands a child precisely that kind of
# stdin -- a pipe the parent never writes to and never closes -- and so do
# several CI runners. With the user's -quit thrown away and no EOF ever coming,
# nothing remained to end the run: Scilab sat in fgets with its script already
# finished until something killed it. core/bug_14901 spawns Scilab this way.
#
# WHY THIS IS A SHELL RUNNER AND NOT A .tst CASE
# ----------------------------------------------
# Holding a pipe open from inside the test harness's host() races with the
# child's open() of the fifo. Measured over three runs of quit_option.tst, that
# shape passed twice and failed once (134 = watchdog aborting a child whose
# open never completed). An intermittent test is worse than no test. Here the
# fifo is opened read-write by THIS shell before the child is started, so a
# writer provably exists before the child ever looks at it, and there is no
# helper process to leak or reap.
#
# EVIDENCE THIS DISCRIMINATES
# ---------------------------
# Run against the pre-fix binary (the build installed in /Applications at the
# time) the same construct returns 124/134 after the full timeout; against the
# fixed build it returns the script's own status in about a second. Point it at
# an old build with SCILAB_BIN to see it fail:
#
#     SCILAB_BIN=/Applications/Scilab-2027.0.0.app/Contents/Resources/scilab/bin/scilab-cli \
#         ./run_quit_open_stdin.sh
#
# Usage:  ./run_quit_open_stdin.sh          # tests the dev-tree build
# Env:    SCILAB_BIN   override the binary under test
#         WAIT_SECONDS how long to allow before declaring a hang (default 45)
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
SCI_ROOT="$(cd "$HERE/../../../.." && pwd)"
BIN="${SCILAB_BIN:-$SCI_ROOT/bin/scilab-cli}"
WAIT="${WAIT_SECONDS:-45}"

if [ ! -x "$BIN" ]; then
    echo "FAIL: no scilab binary at $BIN"
    exit 1
fi

command -v mkfifo >/dev/null || { echo "SKIP: mkfifo unavailable"; exit 0; }

work="$(mktemp -d "${TMPDIR:-/tmp}/quit-open-stdin-XXXXXX")"
trap 'rm -rf "$work"' EXIT

fail=0

# $1 = label, $2 = script body, $3 = expected exit status
probe() {
    label="$1"; body="$2"; want="$3"
    script="$work/probe.sce"
    fifo="$work/fifo"
    printf '%s\n' "$body" > "$script"
    rm -f "$fifo"
    mkfifo "$fifo"

    # Open the fifo read-write in THIS shell FIRST. A writer therefore exists
    # before the child opens it, so the child's open() cannot block and the
    # read never sees EOF -- which is exactly the condition under test.
    exec 3<> "$fifo"

    start=$SECONDS
    # `timeout` is the hang detector: reaching it means -quit did not quit.
    if command -v gtimeout >/dev/null; then TO=gtimeout; else TO=timeout; fi
    "$TO" "$WAIT" "$BIN" -quit -f "$script" < "$fifo" >/dev/null 2>&1
    rc=$?
    elapsed=$((SECONDS - start))

    exec 3>&-
    rm -f "$fifo"

    if [ "$rc" -eq 124 ]; then
        echo "  FAIL  $label: still running after ${WAIT}s -- -quit did not quit"
        fail=1
    elif [ "$rc" -ne "$want" ]; then
        echo "  FAIL  $label: exit $rc, expected $want (after ${elapsed}s)"
        fail=1
    else
        echo "  PASS  $label: exit $rc after ${elapsed}s"
    fi
}

echo "-quit with an open, silent stdin -- $BIN"
probe "clean script quits with 0"      'mprintf("open-stdin case\n");' 0
probe "explicit exit(9) is preserved"  'exit(9);'                      9
probe "uncaught error still reported"  'error("boom");'                16

if [ "$fail" -eq 0 ]; then
    echo "ALL PASS"
else
    echo "FAILURES"
fi
exit "$fail"
